config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  post '/users/sign_in' => 'sessions#create'
  get '/users/sign_in' => 'sessions#new', as: :sign_in

  post '/users/sign_up' => 'users#create'
  get '/users/sign_up' => 'users#new', as: :sign_up

  delete '/users/sign_out' => 'sessions#destroy', as: :sign_out
  get 'active_account/:token' => 'users#active_account', as: :active_account

  get '/users/forgot_password' => 'users#forgot_password'
  post '/users/forgot_password' => 'users#check_email'

  get 'reset_password/:token' => 'users#reset_password', as: :reset_password
  post 'reset_password/:token' => 'users#change_password'

  get '/users/profile' => 'users#profile'

  get 'users/profile/edit' =>'users#edit'
  post 'users/profile/edit' =>'users#edit'

  resources :posts

  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost

  default_scope -> { order(created_at: :desc) }
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments
  

  validates :content, presence: true, length: {minimum: 140}

  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
  include BCrypt
  has_secure_password
  has_many :microposts
  has_many :comments
  before_save {self.email.downcase!}
  before_create :generate_activation_token
  attr_accessor :activation_token
  attr_accessor :remember_token


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  # Validation
  validates :name, presence: true
  validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX, message: 'The email value is invalid' }
  def generate_activation_token
    self.activation_token = SecureRandom.urlsafe_base64
    self.activation_digest = Password.create(self.activation_token)
  end

  def remember
    self.remember_token = SecureRandom.urlsafe_base64
    self.update_attribute :remember_digest, Password.create(self.remember_token)
  end

  def forgot
    self.update_attribute :remember_digest, nil
  end

  def authenticated?(attr,token)
    digest = send("#{attr}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def active_account!
    update_attributes activated: true, activated_at: Time.now, activation_digest: nil
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_action :check_session
  after_action :check_session

  private

  def check_session

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new
    @comment.user_id = params[:comment][:user_id]
    @comment.micropost_id = params[:comment][:micropost_id]
    @comment.content = params[:comment][:content]

    if @comment.save
      redirect_to post_path(@comment.micropost)
    else

    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index

    @posts = Micropost.paginate(:page => params[:page], :per_page => 2)
  end

  def new
    @post = Micropost.new
  end

  def show
    @post = Micropost.find(params[:id])
    @comments = @post.comments
    @comment= Comment.new
  end

  def create
    @post = Micropost.new
    @post.content = params[:micropost][:content]
    @post.user_id = current_user.id
    if @post.save

      redirect_to posts_path
    else
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    @link ='sign_in'
  end

  def create
    @user = User.find_by email: params[:user][:email]

    if @user&.authenticated?(:password, params[:user][:password])
      if @user.activated?
        login(@user)
        params[:user][:remember_me] == '1' ? remember(@user) : forgot(@user)
        flash[:success] = 'You are signed in successfully!'
      else
        flash[:warning] = 'Your account is not actived. Please check your email and active'
      end
      redirect_to root_path
    else
      @user = User.new user_params
      flash.now[:warning] = 'Wrong email or password. please try again!'
      render :new
    end
  end

  def destroy
    cookies.delete :user_id
    cookies.delete :remember_token
    current_user.update_attribute :remember_digest, nil
    session[:user_id] = nil
    flash[:sucess] = 'You are signed out successfully'
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit :email, :password
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @link = 'home'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @link = 'sign_up'
  end

  def create
    @user = User.new user_params
    if @user.save
      UserMailer.account_activation(@user).deliver_now

      flash[:success] = 'You are signed up successfully, please check your email to active your account !!!'
      redirect_to root_path
    else
      flash.now[:warning] = 'Something went wrong'
      render :new
    end
  end
  def active_account
    #tim kiem email
    @user = User.find_by email: params[:email]
      #kiem tra email ton tai va so sanh token voi activation_token trong database
      if @user&.authenticated?(:activation, params[:token]) && @user&.active_account!
        flash[:success] = 'you are actived'
        redirect_to root_path
      else
        flash[:alert] = 'active link is invalid'
      end
  end

  #check password

  def forgot_password
    @user = User.new
  end

  def check_email
    @user = User.find_by email: params[:user][:email]
    if @user
      @user.activation_token = SecureRandom.base64(20)
      @user.activation_digest = BCrypt::Password.create(@user.activation_token)
      @user.update_attributes activation_digest: @user.activation_digest, activation_token: @user.activation_token
      UserMailer.reset_password(@user).deliver_now
      flash[:success] = 'Please check your email to reset password'
      @user = User.new
      render :new
    else
      flash[:warning] = 'Your account does not exist'
      @user = User.new
      render :forgot_password
    end
  end
  #reset password
  def reset_password
    @user = User.new
    @user.email = params[:email]
  end

  def change_password
    @user = User.find_by email: params[:user][:email]
      if @user&.authenticated?(:activation, params[:token])
        @user.update_attributes password: params[:user][:password], activation_digest: nil
        flash[:success] = 'Change password successfully'

        redirect_to root_path
      else
        redirect_to root_path
      end
  end

  def profile
  end

  def edit
    @user = User.new
  end


  private

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login user
    session[:user_id] = user.id
  end

  def current_user

    if (user_id = session[:user_id])
      @current_user = User.find_by id: session[:user_id]
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by id: user_id
      if user && user.authenticated?(:remember, cookies[:remember_token])
        login(user)
      @current_user = user
      end
    end
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forgot(user)
    user.forgot
    cookies.delete[:user_id]
    cookies.delete[:user_id]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def login user
    session[:user_id] = user.id
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="container">
  <p>© Company 2017-2018</p>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="/">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="/posts">Post<span class="sr-only">(current)</span></a>
      </li>
      <% if current_user.present? %>
      <li class="nav-item">
        <a class="nav-link" href="/users/profile"><%= current_user.name %><span class="sr-only">(current)</span></a>
      </li>
        <li>
          <%= link_to 'Sign out', sign_out_path, class: 'nav-link', method: :delete, data: { confirm: 'Are you sure?' } %>
        </li>
      <% else %>
        <% if @link == 'home' %>
          <li class="nav-item active">
            <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
          </li>
        <% else %>
        <li class="nav-item">
          <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
        </li>
        <% end %>

        <% if @link == 'sign_up' %>
        <li class="nav-item active">
          <%= link_to 'Sign up', sign_up_path, class: 'nav-link' %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Sign up', sign_up_path, class: 'nav-link' %>
        </li>
        <% end %>

        <% if @link == 'sign_in' %>
          <li class="nav-item active">
            <%= link_to 'Sign in', sign_in_path, class: 'nav-link' %>
          </li>
        <%else%>
          <li class="nav-item">
            <%= link_to 'Sign in', sign_in_path, class: 'nav-link' %>
          </li>
        <%end%>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <main role='main'>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/index.html.erb
<%= link_to 'Create post', '/posts/new', class: 'btn btn-success' %>

<% @posts.each do |post| %>
  <%= link_to post_path(post) do %>
    <div class="media" >
      <img class="mr-3" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2264%22%20height%3D%2264%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2064%2064%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_167f28eee7d%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A10pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_167f28eee7d%22%3E%3Crect%20width%3D%2264%22%20height%3D%2264%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2212.5546875%22%20y%3D%2236.5%22%3E64x64%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Generic placeholder image">
      <div class="media-body">
      <ab>  <h5><%=post.user.name%></h5>
        <%=post.content%> </ab>
      </div>
    </div>
  <% end %>
<% end %>



<%= will_paginate @products, previous_label: h("<"), next_label: h(">") %>

app/views/posts/new.html.erb
<div class='row justify-content-center align-items-center h-100'>
  <div class='col col-sm-6 col-md-6 col-lg-4 col-xl-3'>
    <h1>Create post</h1>
    <%= form_for @post, url: posts_path do |f| %>
      <div class='form-group'>
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <span class="picture">
        <%= f.file_field :picture %>
      </span>
      <%= f.submit 'Create post', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="media" >
  <img class="mr-3" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2264%22%20height%3D%2264%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2064%2064%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_167f28eee7d%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A10pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_167f28eee7d%22%3E%3Crect%20width%3D%2264%22%20height%3D%2264%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2212.5546875%22%20y%3D%2236.5%22%3E64x64%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Generic placeholder image">
  <div class="media-body">
    <ab>
      <h5><%= @post.user.name %></h5>
      <%= @post.content %>
    </ab>
  </div>
</div>

<%= form_for @comment, url: comments_path, remote: true do |f| %>
  <%= f.text_field :micropost_id, value: @post.id, type: 'hidden' %>
  <%= f.text_field :user_id, value: current_user.id, type: 'hidden' %>
  <div class='form-group'>
    <%= f.text_field :content, class: 'form-control' %>
  </div>
  <%= f.submit 'Comment', class: 'btn btn-primary' %>
<% end %>


<%@comments.each do|comment|%>
<h5><%=comment.user.name%></h5>
<ul>
  <li><%= comment.content%></li>
</ul>
<%end%>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Hello, world!</h1>
    <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
  </div>
</div>

app/views/users/edit.html.erb
<div class='row justify-content-center align-items-center h-100'>
  <div class='col col-sm-6 col-md-6 col-lg-4 col-xl-3'>
    <h1>Edit profile</h1>
    <%= form_for @user, url: '/users/profile/edit' do |f| %>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <div class='form-group'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: current_user.name, value: current_user.name %>
      </div>
      <div class='form-group'>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
        <span class="picture">
          <%= f.file_field :picture %>
        </span>
      </div>
      <input type='hidden' name='user[email]' value='<%= params[:email] %>' >
      <%= f.submit 'Edit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/forgot_password.html.erb
<div class='row justify-content-center align-items-center h-100'>
  <div class='col col-sm-6 col-md-6 col-lg-4 col-xl-3'>
    <h1>Reset password</h1>
    <%= form_for @user, url: '/users/forgot_password' do |f| %>
      <div class='form-group'>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <%= f.submit 'Reset password', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class='row justify-content-center align-items-center h-100'>
  <div class='col col-sm-6 col-md-6 col-lg-4 col-xl-3'>
    <h1>Sign up</h1>
    <%= form_for @user, url: '/users/sign_up' do |f| %>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <div class='form-group'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit 'Sign up', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/profile.html.erb
<div class='row justify-content-center align-items-center h-100'>
  <div class='col col-sm-6 col-md-6 col-lg-4 col-xl-3'>
    <h1>Profile</h1>
      <p><h2>Name: <%= current_user.name %><h2></p>
      <p><h2>Email:<%= current_user.email%></h2></p>
      <a href="/users/profile/edit"><button type="button" class="btn btn-info">Edit profile</button></a>
  </div>
</div>

app/views/users/reset_password.html.erb
<div class='row justify-content-center align-items-center h-100'>
  <div class='col col-sm-6 col-md-6 col-lg-4 col-xl-3'>
    <h1>Reset password</h1>
    <%= form_for @user, url: params[:token] do |f| %>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <div class='form-group'>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <input type='hidden' name='user[email]' value='<%= params[:email] %>' >
      <%= f.submit 'Change password', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>